name: marckeating
favicon: null
layout_spectrum: 0.21086758514866233
typography_spectrum: 0.3025158520322293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7416794677264988
  lightness: 0.5965209293644875
  saturation: 0.26765634678304195
  rhythmicContrast: 0.015519744716584682
purpose: []
