name: marckeating
favicon: null
layout_spectrum: 0.18311
typography_spectrum: 0.21441
title: marckeating
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7416794677264988
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
